#!/usr/bin/env python3
"""Write docs/supported-models.md from data/models/*.json."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
from alienfix import models  # noqa: E402

CTRL = {"elc": "AW-ELC (USB 187c:0550/0551)", "legacy": "AlienFX legacy (USB 187c:05xx)",
        "wmi": "kernel alienware-wmi"}
KB = {"per-key": "per-key (Darfon, needs a key map)", "zones": "zones", "none": "—"}


def main():
    ms = sorted(models.load(ROOT / "data/models").values(),
                key=lambda m: (m["support"] != "verified", m["name"].lower()))
    out = ["# Supported models", "",
           "Generated by `tools/list_models.py` from `data/models/`. **Verified** means",
           "checked on the real machine with a camera. **Reported** means taken from",
           "other open-source projects' community mappings (alienfx-tools, akbl,",
           "OpenRGB, AWCC) and not verified by this project: expect wrong zone names",
           "or indices, and please report what you see.", "",
           "A machine that matches nothing still works: the daemon builds a generic",
           "model from the controllers it finds (neutral zone names), and a per-key",
           "keyboard can be mapped with the blink wizard.", "",
           "| Model | Status | Matched by | Keyboard | Zones | Controller | Source |",
           "|---|---|---|---|---|---|---|"]
    import json
    shipped = {json.loads(p.read_text())["chassis"] for p in (ROOT / "data/profiles").glob("*.json")}
    for m in ms:
        kb = KB[m["keyboard"]["type"]]
        if set(m["keyboard"].get("chassis", [])) & shipped:
            kb = "per-key (key map shipped)"
        match = ", ".join(m.get("dmi_product", [])) or ", ".join(f"USB {u}" for u in m.get("usb", [])) \
            or "manual choice"
        ctrl = ", ".join(sorted({CTRL[z["controller"]] for z in m["zones"]}))
        zones = ", ".join(z["label"] for z in m["zones"])
        out.append(f"| {m['name']} | {m['support']} | {match} | {kb} | "
                   f"{zones} | {ctrl} | {m.get('source', '').replace('|', '/')} |")
    out.append("")
    (ROOT / "docs/supported-models.md").write_text("\n".join(out))
    print(len(ms), "models")


if __name__ == "__main__":
    main()
